# Generated by Django 4.1.7 on 2023-03-17 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='owner',
        ),
    ]
